excluded:
  - .build
  - dist

disabled_rules:
  - trailing_comma
  - statement_position

identifier_name:
  min_length: 1
  max_length: 60

type_name:
  max_length: 60

line_length:
  warning: 160
  error: 200

file_length:
  warning: 800
  error: 1200

type_body_length:
  warning: 600
  error: 900

function_body_length:
  warning: 80
  error: 120

function_parameter_count:
  warning: 8
  error: 12
